### ISSUE TITLE
Could not pass event InventoryClickEvent 

### ISSUE THREAD

**Issue by AlekseyVideman** [ssomar1607/ExecutableItems#2]
[04:51:42 ERROR]: Could not pass event InventoryClickEvent to ExecutableItems v1.7.8
java.lang.NullPointerException: null
        at com.ssomar.executableitems.events.InteractionGUI.onInvClick(InteractionGUI.java:27) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor105.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2393) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:32) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:43) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1162) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1155) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1131) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:974) ~[tuinity-1.15.2.jar:git-Tuinity-"126d3cc"]
        at java.lang.Thread.run(Thread.java:832) [?:?]

**Comment by ssomar1607** [comment]
[ei.zip](https://github.com/ssomar1607/ExecutableItems/files/4844549/ei.zip)
Try this version :D normaly its fix

**Comment by AlekseyVideman** [comment]
> [ei.zip](https://github.com/ssomar1607/ExecutableItems/files/4844549/ei.zip)
> Try this version :D normaly its fix

Thanks!
